# -*- coding: utf-8 -*-
"""NLP_Course_Practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFSt0zyWtd3BLI0UpGpVPxfAYsxQG7c9
"""

import tensorflow as tf

from tensorflow import keras

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences =[
            'I really love my dog',
            'I really love my cat',
            'I really love Ahnaf vaia',
            'I really hate you',
            'দেশে করোনা রোগী বেড়ে যাওয়ায় হাসপাতালগুলোতে আইসিইউ ও হাই ফ্লো নাজাল ক্যানুলা সংকটের বিষয়টি নতুন করে সামনে এসেছে। গুরুতর অসুস্থ রোগীদের উচ্চমাত্রায় অক্সিজেন সরবরাহের জন্য আইসিইউ বা হাই ফ্লো নাজাল ক্যানুলার দরকার হয়। এই সংকটের মধ্যে কিছুটা স্বস্তির খবর হয়ে এসেছে বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয়ের (বুয়েট) একদল শিক্ষক-শিক্ষার্থীর উদ্ভাবিত ‘অক্সিজেট’ নামের একটি যন্ত্র।'
]

anotherExample=[
                'I really love my dog',
                'I really love my cat',
                'Do you think my dog is amazing?'
]

test_sq = tokenizer.texts_to_sequences(anotherExample)

print(anotherExample)

tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")

tokenizer.fit_on_texts(anotherExample)

word_index = tokenizer.word_index

print(word_index)

test_seq = tokenizer.texts_to_sequences(sentences)

padded= pad_sequences(test_seq)

paddedAnother = pad_sequences(test_seq,padding='post',maxlen=10)

print(test_seq)

print(padded)

print(paddedAnother)

print(word_index)

print(test_sq)